### ISSUE TITLE
Custom commands

### ISSUE THREAD

**Issue by Patryk27** [Patryk27/janet#5]
It should be possible to create custom commands, e.g. by configuring them inside the `config.toml` file:

```toml
[[commands]]
trigger = "merge-request-comment"
match = "run pipeline (%d)"
launch = "./some-script.sh"
```
